services:
  - type: web
    name: f1project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn f1project.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: f1betting-db
          property: connectionString

databases:
  - name: f1betting-db
    databaseName: f1betting
    user: ivanprocaccino