# Generated by Django 4.2.20 on 2025-03-22 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('team', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race_date', models.DateTimeField()),
                ('practice_start', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('dnf_count', models.IntegerField(blank=True, null=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.circuit')),
            ],
            options={
                'ordering': ['race_date'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnf_count', models.IntegerField()),
                ('first_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='betting.driver')),
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='betting.race')),
                ('second_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='betting.driver')),
                ('third_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='betting.driver')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='betting.season'),
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnf_prediction', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField(default=0)),
                ('first_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='betting.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='betting.race')),
                ('second_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='betting.driver')),
                ('third_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='betting.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'race')},
            },
        ),
    ]
