# Generated by Django 4.2.20 on 2025-03-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='first_place',
            new_name='first_place_race',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='second_place',
            new_name='second_place_race',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='third_place',
            new_name='third_place_race',
        ),
        migrations.RenameField(
            model_name='raceresult',
            old_name='first_place',
            new_name='first_place_race',
        ),
        migrations.RenameField(
            model_name='raceresult',
            old_name='second_place',
            new_name='second_place_race',
        ),
        migrations.RenameField(
            model_name='raceresult',
            old_name='third_place',
            new_name='third_place_race',
        ),
        migrations.AddField(
            model_name='bet',
            name='first_place_quali',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='betting.driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='second_place_quali',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='betting.driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='third_place_quali',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='betting.driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='is_sprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='first_place_quali',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='betting.driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raceresult',
            name='second_place_quali',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='betting.driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raceresult',
            name='third_place_quali',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='betting.driver'),
            preserve_default=False,
        ),
    ]
