# Generated by Django 4.2.20 on 2025-03-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_rename_first_place_bet_first_place_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
