# Generated by Django 4.2.20 on 2025-03-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_alter_bet_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='extraPoints',
            field=models.FloatField(default=0.0),
        ),
    ]
